
server:
  port: 8080
spring:
  application:
    name: movie-reservation-service
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL_PROD}
    username: ${DB_USERNAME_PROD}
    password: ${DB_PASSWORD_PROD}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
